# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.welcome_tab = QtWidgets.QWidget()
        self.welcome_tab.setObjectName("welcome_tab")
        self.user_btn = QtWidgets.QPushButton(self.welcome_tab)
        self.user_btn.setGeometry(QtCore.QRect(230, 230, 93, 28))
        self.user_btn.setObjectName("user_btn")
        self.audit_btn = QtWidgets.QPushButton(self.welcome_tab)
        self.audit_btn.setGeometry(QtCore.QRect(420, 230, 93, 28))
        self.audit_btn.setObjectName("audit_btn")
        self.tabWidget.addTab(self.welcome_tab, "")
        self.user_tab = QtWidgets.QWidget()
        self.user_tab.setObjectName("user_tab")
        self.label_user = QtWidgets.QLabel(self.user_tab)
        self.label_user.setGeometry(QtCore.QRect(20, 70, 55, 16))
        self.label_user.setObjectName("label_user")
        self.back_btn_user = QtWidgets.QPushButton(self.user_tab)
        self.back_btn_user.setGeometry(QtCore.QRect(540, 370, 93, 28))
        self.back_btn_user.setObjectName("back_btn_user")
        self.display_label = QtWidgets.QLabel(self.user_tab)
        self.display_label.setGeometry(QtCore.QRect(90, 60, 491, 261))
        self.display_label.setText("")
        self.display_label.setObjectName("display_label")
        self.tabWidget.addTab(self.user_tab, "")
        self.audit_tab = QtWidgets.QWidget()
        self.audit_tab.setObjectName("audit_tab")
        self.label_audit = QtWidgets.QLabel(self.audit_tab)
        self.label_audit.setGeometry(QtCore.QRect(60, 70, 55, 16))
        self.label_audit.setObjectName("label_audit")
        self.pushButton_browse_audit = QtWidgets.QPushButton(self.audit_tab)
        self.pushButton_browse_audit.setGeometry(QtCore.QRect(320, 260, 93, 28))
        self.pushButton_browse_audit.setObjectName("pushButton_browse_audit")
        self.back_btn_audit = QtWidgets.QPushButton(self.audit_tab)
        self.back_btn_audit.setGeometry(QtCore.QRect(610, 20, 93, 28))
        self.back_btn_audit.setObjectName("back_btn_audit")
        self.widget = QtWidgets.QWidget(self.audit_tab)
        self.widget.setGeometry(QtCore.QRect(70, 200, 201, 24))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.password_label = QtWidgets.QLabel(self.widget)
        self.password_label.setObjectName("password_label")
        self.horizontalLayout.addWidget(self.password_label)
        self.lineEdit_password_audit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_password_audit.setObjectName("lineEdit_password_audit")
        self.horizontalLayout.addWidget(self.lineEdit_password_audit)
        self.label_excel = QtWidgets.QLabel(self.audit_tab)
        self.label_excel.setGeometry(QtCore.QRect(71, 261, 29, 16))
        self.label_excel.setObjectName("label_excel")
        self.lineEdit_Excel_audit = QtWidgets.QLineEdit(self.audit_tab)
        self.lineEdit_Excel_audit.setGeometry(QtCore.QRect(107, 261, 137, 22))
        self.lineEdit_Excel_audit.setReadOnly(True)
        self.lineEdit_Excel_audit.setObjectName("lineEdit_Excel_audit")
        self.tabWidget.addTab(self.audit_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JAKYA"))
        self.user_btn.setText(_translate("MainWindow", "User Mode"))
        self.audit_btn.setText(_translate("MainWindow", "Audit Mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.welcome_tab), _translate("MainWindow", "Welcome"))
        self.label_user.setText(_translate("MainWindow", "User"))
        self.back_btn_user.setText(_translate("MainWindow", "Back"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.user_tab), _translate("MainWindow", "User Mode"))
        self.label_audit.setText(_translate("MainWindow", "Audit"))
        self.pushButton_browse_audit.setText(_translate("MainWindow", "Browse"))
        self.back_btn_audit.setText(_translate("MainWindow", "Back"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.label_excel.setText(_translate("MainWindow", "Excel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.audit_tab), _translate("MainWindow", "Audit Mode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
