# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setStyleSheet("/* Main Window */\n"
"QMainWindow {\n"
"    background-color: #f0f4f8;\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"}\n"
"\n"
"/* Tab Widget */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #cccccc;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #dce4ec;\n"
"    color: #004c8c;\n"
"    border: 1px solid #aaaaaa;\n"
"    padding: 10px;\n"
"    min-width: 120px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #004c8c;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    color: #004c8c;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Push Buttons */\n"
"QPushButton {\n"
"    background-color: #008cba;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005f7a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003f50;\n"
"}\n"
"\n"
"/* Group Boxes */\n"
"QGroupBox {\n"
"    border: 2px solid #004c8c;\n"
"    border-radius: 5px;\n"
"    margin-top: 20px;\n"
"    color: #004c8c;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* Text Edit */\n"
"QTextEdit {\n"
"    background-color: #ffffff;\n"
"    color: #004c8c;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"/* Line Edit */\n"
"QLineEdit {\n"
"    background-color: #ffffff;\n"
"    color: #004c8c;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* Combo Box */\n"
"QComboBox {\n"
"    background-color: #ffffff;\n"
"    color: #004c8c;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #008cba;\n"
"}\n"
"\n"
"/* Status Bar */\n"
"QStatusBar {\n"
"    background-color: #004c8c;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Scroll Bar */\n"
"QScrollBar:vertical {\n"
"    background-color: #dce4ec;\n"
"    width: 12px;\n"
"    margin: 20px 0 20px 0;\n"
"    border: 1px solid #aaaaaa;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #004c8c;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background-color: #dce4ec;\n"
"    border: 1px solid #aaaaaa;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Tool Bar */\n"
"QToolBar {\n"
"    background-color: #004c8c;\n"
"    border-bottom: 1px solid #cccccc;\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: #005f7a;\n"
"}")
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly|QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhEmailCharactersOnly|QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhLatinOnly|QtCore.Qt.ImhLowercaseOnly|QtCore.Qt.ImhUppercaseOnly|QtCore.Qt.ImhUrlCharactersOnly)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.welcome_tab = QtWidgets.QWidget()
        self.welcome_tab.setObjectName("welcome_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.welcome_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(628, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem2 = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.label_6 = QtWidgets.QLabel(self.welcome_tab)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        spacerItem4 = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem5 = QtWidgets.QSpacerItem(270, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.validation_label_6 = QtWidgets.QLabel(self.welcome_tab)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.validation_label_6.setFont(font)
        self.validation_label_6.setObjectName("validation_label_6")
        self.verticalLayout_3.addWidget(self.validation_label_6)
        spacerItem6 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.user_btn = QtWidgets.QPushButton(self.welcome_tab)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.user_btn.setFont(font)
        self.user_btn.setObjectName("user_btn")
        self.horizontalLayout_5.addWidget(self.user_btn)
        self.audit_btn = QtWidgets.QPushButton(self.welcome_tab)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.audit_btn.setFont(font)
        self.audit_btn.setObjectName("audit_btn")
        self.horizontalLayout_5.addWidget(self.audit_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        spacerItem8 = QtWidgets.QSpacerItem(240, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11.addLayout(self.verticalLayout_9)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.update = QtWidgets.QPushButton(self.welcome_tab)
        self.update.setObjectName("update")
        self.gridLayout_4.addWidget(self.update, 3, 1, 1, 1)
        self.ask = QtWidgets.QLabel(self.welcome_tab)
        self.ask.setObjectName("ask")
        self.gridLayout_4.addWidget(self.ask, 3, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.welcome_tab)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 2px solid #2196F3;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"    color: black;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #2196F3;\n"
"    width: 20px;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 5, 0, 1, 2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.welcome_tab)
        self.label.setMinimumSize(QtCore.QSize(125, 91))
        self.label.setMaximumSize(QtCore.QSize(121, 91))
        self.label.setStyleSheet("background-image: url(:/logo/BrightLogo.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        spacerItem9 = QtWidgets.QSpacerItem(17, 358, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.check = QtWidgets.QPushButton(self.welcome_tab)
        self.check.setObjectName("check")
        self.gridLayout_4.addWidget(self.check, 6, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.welcome_tab)
        self.label_5.setMinimumSize(QtCore.QSize(61, 16))
        self.label_5.setMaximumSize(QtCore.QSize(291, 41))
        self.label_5.setStyleSheet("")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 7, 1, 1, 1)
        self.validation_label = QtWidgets.QLabel(self.welcome_tab)
        self.validation_label.setMinimumSize(QtCore.QSize(0, 16))
        self.validation_label.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.validation_label.setFont(font)
        self.validation_label.setObjectName("validation_label")
        self.gridLayout_4.addWidget(self.validation_label, 7, 0, 1, 1)
        self.tabWidget.addTab(self.welcome_tab, "")
        self.user_tab = QtWidgets.QWidget()
        self.user_tab.setObjectName("user_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.user_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.back_btn_user = QtWidgets.QPushButton(self.user_tab)
        self.back_btn_user.setMinimumSize(QtCore.QSize(25, 25))
        self.back_btn_user.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.back_btn_user.setFont(font)
        self.back_btn_user.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;    /* Background color of the button */\n"
"    border: none;                 /* Remove default border */\n"
"    border-radius: 12px;          /* Makes the button circular (half of width/height) */\n"
"    width: 25px;                  /* Width of the button */\n"
"    height: 25px;                 /* Height of the button */\n"
"    color: white;                 /* Color of the arrow */\n"
"    font-size:25px;              /* Size of the arrow */\n"
"    font-weight: bold;            /* Bold arrow */\n"
"    text-align: center;           /* Center the arrow */\n"
"    padding: 0px;                 /* Remove any padding */\n"
"}\n"
"")
        self.back_btn_user.setObjectName("back_btn_user")
        self.verticalLayout_2.addWidget(self.back_btn_user)
        spacerItem10 = QtWidgets.QSpacerItem(20, 148, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem11 = QtWidgets.QSpacerItem(572, 88, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.label_2 = QtWidgets.QLabel(self.user_tab)
        self.label_2.setMinimumSize(QtCore.QSize(125, 91))
        self.label_2.setMaximumSize(QtCore.QSize(121, 91))
        self.label_2.setStyleSheet("background-image: url(:/logo/BrightLogo.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        spacerItem12 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem12)
        self.scan_user = QtWidgets.QLineEdit(self.user_tab)
        self.scan_user.setMinimumSize(QtCore.QSize(1, 0))
        self.scan_user.setMaximumSize(QtCore.QSize(2, 16777215))
        self.scan_user.setStyleSheet("QLineEdit {\n"
"                border: 2px solid white;\n"
"                color: white;\n"
"                background-color: transparent; /* Optional: makes the background transparent */\n"
"            }")
        self.scan_user.setText("")
        self.scan_user.setObjectName("scan_user")
        self.verticalLayout_7.addWidget(self.scan_user)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_9 = QtWidgets.QLabel(self.user_tab)
        self.label_9.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_51.addWidget(self.label_9)
        self.asset_name = QtWidgets.QTextBrowser(self.user_tab)
        self.asset_name.setMinimumSize(QtCore.QSize(256, 29))
        self.asset_name.setMaximumSize(QtCore.QSize(500, 33))
        self.asset_name.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.asset_name.setObjectName("asset_name")
        self.horizontalLayout_51.addWidget(self.asset_name)
        self.verticalLayout_4.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.label_15 = QtWidgets.QLabel(self.user_tab)
        self.label_15.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_52.addWidget(self.label_15)
        self.asset_tag = QtWidgets.QTextBrowser(self.user_tab)
        self.asset_tag.setMinimumSize(QtCore.QSize(256, 0))
        self.asset_tag.setMaximumSize(QtCore.QSize(500, 33))
        self.asset_tag.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.asset_tag.setObjectName("asset_tag")
        self.horizontalLayout_52.addWidget(self.asset_tag)
        self.verticalLayout_4.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label_16 = QtWidgets.QLabel(self.user_tab)
        self.label_16.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_53.addWidget(self.label_16)
        self.serial = QtWidgets.QTextBrowser(self.user_tab)
        self.serial.setMinimumSize(QtCore.QSize(256, 0))
        self.serial.setMaximumSize(QtCore.QSize(500, 33))
        self.serial.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.serial.setObjectName("serial")
        self.horizontalLayout_53.addWidget(self.serial)
        self.verticalLayout_4.addLayout(self.horizontalLayout_53)
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.label_17 = QtWidgets.QLabel(self.user_tab)
        self.label_17.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_54.addWidget(self.label_17)
        self.checked_out_to = QtWidgets.QTextBrowser(self.user_tab)
        self.checked_out_to.setMinimumSize(QtCore.QSize(256, 0))
        self.checked_out_to.setMaximumSize(QtCore.QSize(500, 33))
        self.checked_out_to.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.checked_out_to.setObjectName("checked_out_to")
        self.horizontalLayout_54.addWidget(self.checked_out_to)
        self.verticalLayout_4.addLayout(self.horizontalLayout_54)
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.label_18 = QtWidgets.QLabel(self.user_tab)
        self.label_18.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_55.addWidget(self.label_18)
        self.owner = QtWidgets.QTextBrowser(self.user_tab)
        self.owner.setMinimumSize(QtCore.QSize(256, 0))
        self.owner.setMaximumSize(QtCore.QSize(500, 33))
        self.owner.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.owner.setObjectName("owner")
        self.horizontalLayout_55.addWidget(self.owner)
        self.verticalLayout_4.addLayout(self.horizontalLayout_55)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        spacerItem13 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem13)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 1, 0, 1, 2)
        self.validation_label_2 = QtWidgets.QLabel(self.user_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.validation_label_2.setFont(font)
        self.validation_label_2.setObjectName("validation_label_2")
        self.gridLayout_2.addWidget(self.validation_label_2, 2, 0, 1, 2)
        self.tabWidget.addTab(self.user_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.back_btn_user_2 = QtWidgets.QPushButton(self.tab)
        self.back_btn_user_2.setMinimumSize(QtCore.QSize(25, 25))
        self.back_btn_user_2.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.back_btn_user_2.setFont(font)
        self.back_btn_user_2.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;    /* Background color of the button */\n"
"    border: none;                 /* Remove default border */\n"
"    border-radius: 12px;          /* Makes the button circular (half of width/height) */\n"
"    width: 25px;                  /* Width of the button */\n"
"    height: 25px;                 /* Height of the button */\n"
"    color: white;                 /* Color of the arrow */\n"
"    font-size:25px;              /* Size of the arrow */\n"
"    font-weight: bold;            /* Bold arrow */\n"
"    text-align: center;           /* Center the arrow */\n"
"    padding: 0px;                 /* Remove any padding */\n"
"}\n"
"")
        self.back_btn_user_2.setObjectName("back_btn_user_2")
        self.verticalLayout_12.addWidget(self.back_btn_user_2)
        spacerItem14 = QtWidgets.QSpacerItem(20, 148, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem14)
        self.gridLayout_3.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem15 = QtWidgets.QSpacerItem(710, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem15)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setMinimumSize(QtCore.QSize(125, 91))
        self.label_10.setMaximumSize(QtCore.QSize(121, 91))
        self.label_10.setStyleSheet("background-image: url(:/logo/BrightLogo.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_20.addWidget(self.label_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        spacerItem16 = QtWidgets.QSpacerItem(20, 138, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem16)
        self.gridLayout_3.addLayout(self.verticalLayout_11, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.password_label_2 = QtWidgets.QLabel(self.tab)
        self.password_label_2.setMinimumSize(QtCore.QSize(0, 33))
        self.password_label_2.setMaximumSize(QtCore.QSize(110, 33))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.password_label_2.setFont(font)
        self.password_label_2.setMouseTracking(False)
        self.password_label_2.setObjectName("password_label_2")
        self.verticalLayout_16.addWidget(self.password_label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_excel = QtWidgets.QLabel(self.tab)
        self.label_excel.setMinimumSize(QtCore.QSize(0, 33))
        self.label_excel.setMaximumSize(QtCore.QSize(110, 33))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_excel.setFont(font)
        self.label_excel.setObjectName("label_excel")
        self.horizontalLayout.addWidget(self.label_excel)
        spacerItem17 = QtWidgets.QSpacerItem(45, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem17)
        self.verticalLayout_16.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_16)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lineEdit_password_audit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_password_audit_2.setMinimumSize(QtCore.QSize(500, 33))
        self.lineEdit_password_audit_2.setMaximumSize(QtCore.QSize(500, 33))
        self.lineEdit_password_audit_2.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoEditMenu|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhNoTextHandles|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_password_audit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_audit_2.setObjectName("lineEdit_password_audit_2")
        self.verticalLayout_10.addWidget(self.lineEdit_password_audit_2)
        self.lineEdit_excel_audit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_excel_audit.setMinimumSize(QtCore.QSize(500, 33))
        self.lineEdit_excel_audit.setMaximumSize(QtCore.QSize(500, 33))
        self.lineEdit_excel_audit.setObjectName("lineEdit_excel_audit")
        self.verticalLayout_10.addWidget(self.lineEdit_excel_audit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pushButton_login = QtWidgets.QPushButton(self.tab)
        self.pushButton_login.setMinimumSize(QtCore.QSize(60, 33))
        self.pushButton_login.setMaximumSize(QtCore.QSize(60, 33))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setObjectName("pushButton_login")
        self.verticalLayout_14.addWidget(self.pushButton_login)
        self.pushButton_browse_audit = QtWidgets.QPushButton(self.tab)
        self.pushButton_browse_audit.setMinimumSize(QtCore.QSize(60, 33))
        self.pushButton_browse_audit.setMaximumSize(QtCore.QSize(49, 33))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_browse_audit.setFont(font)
        self.pushButton_browse_audit.setObjectName("pushButton_browse_audit")
        self.verticalLayout_14.addWidget(self.pushButton_browse_audit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.right = QtWidgets.QLabel(self.tab)
        self.right.setMinimumSize(QtCore.QSize(30, 30))
        self.right.setMaximumSize(QtCore.QSize(30, 30))
        self.right.setStyleSheet("background-image: url(:/Pass_check/password.jpg);\n"
"background-image: url(:/Pass_check/right sign.jpg);")
        self.right.setText("")
        self.right.setObjectName("right")
        self.verticalLayout_15.addWidget(self.right)
        spacerItem18 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_15.addItem(spacerItem18)
        spacerItem19 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_15.addItem(spacerItem19)
        self.horizontalLayout_3.addLayout(self.verticalLayout_15)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 1, 2)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem20 = QtWidgets.QSpacerItem(20, 118, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem20)
        self.validation_label_7 = QtWidgets.QLabel(self.tab)
        self.validation_label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.validation_label_7.setFont(font)
        self.validation_label_7.setObjectName("validation_label_7")
        self.verticalLayout_13.addWidget(self.validation_label_7)
        self.gridLayout_3.addLayout(self.verticalLayout_13, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.audit_tab = QtWidgets.QWidget()
        self.audit_tab.setObjectName("audit_tab")
        self.layoutWidget = QtWidgets.QWidget(self.audit_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(42, 9, 729, 148))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem21 = QtWidgets.QSpacerItem(698, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem21)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(125, 91))
        self.label_3.setMaximumSize(QtCore.QSize(121, 91))
        self.label_3.setStyleSheet("background-image: url(:/logo/BrightLogo.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_21.addWidget(self.label_3)
        self.verticalLayout_20.addLayout(self.horizontalLayout_21)
        spacerItem22 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem22)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.start_scan_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.start_scan_label.setFont(font)
        self.start_scan_label.setObjectName("start_scan_label")
        self.horizontalLayout_48.addWidget(self.start_scan_label)
        spacerItem23 = QtWidgets.QSpacerItem(238, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem23)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_audit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_audit.setMinimumSize(QtCore.QSize(1, 0))
        self.lineEdit_audit.setMaximumSize(QtCore.QSize(2, 16777215))
        self.lineEdit_audit.setStyleSheet("QLineEdit {\n"
"                border: 2px solid white;\n"
"                color: white;\n"
"                background-color: transparent; /* Optional: makes the background transparent */\n"
"            }")
        self.lineEdit_audit.setText("")
        self.lineEdit_audit.setObjectName("lineEdit_audit")
        self.horizontalLayout_2.addWidget(self.lineEdit_audit)
        self.horizontalLayout_48.addLayout(self.horizontalLayout_2)
        spacerItem24 = QtWidgets.QSpacerItem(258, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem24)
        self.verticalLayout_20.addLayout(self.horizontalLayout_48)
        self.layoutWidget1 = QtWidgets.QWidget(self.audit_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(9, 9, 27, 131))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.back_btn_audit = QtWidgets.QPushButton(self.layoutWidget1)
        self.back_btn_audit.setMinimumSize(QtCore.QSize(25, 25))
        self.back_btn_audit.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.back_btn_audit.setFont(font)
        self.back_btn_audit.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;    /* Background color of the button */\n"
"    border: none;                 /* Remove default border */\n"
"    border-radius: 12px;          /* Makes the button circular (half of width/height) */\n"
"    width: 25px;                  /* Width of the button */\n"
"    height: 25px;                 /* Height of the button */\n"
"    color: white;                 /* Color of the arrow */\n"
"    font-size:25px;              /* Size of the arrow */\n"
"    font-weight: bold;            /* Bold arrow */\n"
"    text-align: center;           /* Center the arrow */\n"
"    padding: 0px;                 /* Remove any padding */\n"
"}\n"
"")
        self.back_btn_audit.setObjectName("back_btn_audit")
        self.gridLayout_7.addWidget(self.back_btn_audit, 0, 0, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(20, 98, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem25, 1, 0, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.audit_tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(9, 163, 759, 351))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_43.addWidget(self.label_8)
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.textBrowser_6.setMinimumSize(QtCore.QSize(256, 29))
        self.textBrowser_6.setMaximumSize(QtCore.QSize(500, 33))
        self.textBrowser_6.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.horizontalLayout_43.addWidget(self.textBrowser_6)
        self.verticalLayout.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_44.addWidget(self.label_11)
        self.textBrowser_13 = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.textBrowser_13.setMinimumSize(QtCore.QSize(256, 0))
        self.textBrowser_13.setMaximumSize(QtCore.QSize(500, 33))
        self.textBrowser_13.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.horizontalLayout_44.addWidget(self.textBrowser_13)
        self.verticalLayout.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_45.addWidget(self.label_12)
        self.textBrowser_14 = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.textBrowser_14.setMinimumSize(QtCore.QSize(256, 0))
        self.textBrowser_14.setMaximumSize(QtCore.QSize(500, 33))
        self.textBrowser_14.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.horizontalLayout_45.addWidget(self.textBrowser_14)
        self.verticalLayout.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_46.addWidget(self.label_13)
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.textBrowser_15.setMinimumSize(QtCore.QSize(256, 0))
        self.textBrowser_15.setMaximumSize(QtCore.QSize(500, 33))
        self.textBrowser_15.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.horizontalLayout_46.addWidget(self.textBrowser_15)
        self.verticalLayout.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_47.addWidget(self.label_14)
        self.textBrowser_16 = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.textBrowser_16.setMinimumSize(QtCore.QSize(256, 0))
        self.textBrowser_16.setMaximumSize(QtCore.QSize(500, 33))
        self.textBrowser_16.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.horizontalLayout_47.addWidget(self.textBrowser_16)
        self.verticalLayout.addLayout(self.horizontalLayout_47)
        self.verticalLayout_18.addLayout(self.verticalLayout)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.FinishAudit = QtWidgets.QPushButton(self.layoutWidget2)
        self.FinishAudit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.FinishAudit.setFont(font)
        self.FinishAudit.setObjectName("FinishAudit")
        self.horizontalLayout_13.addWidget(self.FinishAudit)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_13.addItem(spacerItem26)
        self.ShowStatistics = QtWidgets.QPushButton(self.layoutWidget2)
        self.ShowStatistics.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.ShowStatistics.setFont(font)
        self.ShowStatistics.setObjectName("ShowStatistics")
        self.horizontalLayout_13.addWidget(self.ShowStatistics)
        self.verticalLayout_18.addLayout(self.horizontalLayout_13)
        self.verticalLayout_22.addLayout(self.verticalLayout_18)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem27 = QtWidgets.QSpacerItem(428, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem27)
        spacerItem28 = QtWidgets.QSpacerItem(20, 84, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_8.addItem(spacerItem28)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem29)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.validation_label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.validation_label_4.setMinimumSize(QtCore.QSize(35, 24))
        self.validation_label_4.setMaximumSize(QtCore.QSize(30, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.validation_label_4.setFont(font)
        self.validation_label_4.setObjectName("validation_label_4")
        self.verticalLayout_19.addWidget(self.validation_label_4)
        self.validation_label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.validation_label_5.setMinimumSize(QtCore.QSize(30, 24))
        self.validation_label_5.setMaximumSize(QtCore.QSize(30, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.validation_label_5.setFont(font)
        self.validation_label_5.setObjectName("validation_label_5")
        self.verticalLayout_19.addWidget(self.validation_label_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout_19)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.textBrowser_4.setMinimumSize(QtCore.QSize(200, 0))
        self.textBrowser_4.setMaximumSize(QtCore.QSize(200, 33))
        self.textBrowser_4.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.verticalLayout_17.addWidget(self.textBrowser_4)
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.textBrowser_5.setMinimumSize(QtCore.QSize(200, 0))
        self.textBrowser_5.setMaximumSize(QtCore.QSize(200, 33))
        self.textBrowser_5.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.verticalLayout_17.addWidget(self.textBrowser_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout_17)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_7)
        self.verticalLayout_22.addLayout(self.horizontalLayout_15)
        self.validation_label_3 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.validation_label_3.setFont(font)
        self.validation_label_3.setObjectName("validation_label_3")
        self.verticalLayout_22.addWidget(self.validation_label_3)
        self.tabWidget.addTab(self.audit_tab, "")
        self.Statistics_tab = QtWidgets.QWidget()
        self.Statistics_tab.setObjectName("Statistics_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Statistics_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.back_btn_stats = QtWidgets.QPushButton(self.Statistics_tab)
        self.back_btn_stats.setMinimumSize(QtCore.QSize(25, 25))
        self.back_btn_stats.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.back_btn_stats.setFont(font)
        self.back_btn_stats.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;    /* Background color of the button */\n"
"    border: none;                 /* Remove default border */\n"
"    border-radius: 12px;          /* Makes the button circular (half of width/height) */\n"
"    width: 25px;                  /* Width of the button */\n"
"    height: 25px;                 /* Height of the button */\n"
"    color: white;                 /* Color of the arrow */\n"
"    font-size:25px;              /* Size of the arrow */\n"
"    font-weight: bold;            /* Bold arrow */\n"
"    text-align: center;           /* Center the arrow */\n"
"    padding: 0px;                 /* Remove any padding */\n"
"}\n"
"")
        self.back_btn_stats.setObjectName("back_btn_stats")
        self.verticalLayout_21.addWidget(self.back_btn_stats)
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem30)
        self.gridLayout_5.addLayout(self.verticalLayout_21, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.Statistics_tab)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 1, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem31)
        self.label_4 = QtWidgets.QLabel(self.Statistics_tab)
        self.label_4.setMinimumSize(QtCore.QSize(125, 91))
        self.label_4.setMaximumSize(QtCore.QSize(121, 91))
        self.label_4.setStyleSheet("background-image: url(:/logo/BrightLogo.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_14.addWidget(self.label_4)
        self.gridLayout_5.addLayout(self.horizontalLayout_14, 0, 2, 1, 1)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.Statistics_tab)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.horizontalLayout_16.addWidget(self.graphicsView_2)
        self.graphicsView = QtWidgets.QGraphicsView(self.Statistics_tab)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_16.addWidget(self.graphicsView)
        self.verticalLayout_23.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.Statistics_tab)
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.horizontalLayout_17.addWidget(self.graphicsView_4)
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.Statistics_tab)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.horizontalLayout_17.addWidget(self.graphicsView_5)
        self.verticalLayout_23.addLayout(self.horizontalLayout_17)
        self.gridLayout_5.addLayout(self.verticalLayout_23, 1, 0, 1, 3)
        self.validation_label_8 = QtWidgets.QLabel(self.Statistics_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.validation_label_8.setFont(font)
        self.validation_label_8.setObjectName("validation_label_8")
        self.gridLayout_5.addWidget(self.validation_label_8, 2, 0, 1, 2)
        self.tabWidget.addTab(self.Statistics_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JAKYA"))
        self.label_6.setText(_translate("MainWindow", "Asset Management Tool"))
        self.validation_label_6.setText(_translate("MainWindow", "  Select Mode"))
        self.user_btn.setText(_translate("MainWindow", "User Mode"))
        self.audit_btn.setText(_translate("MainWindow", "Audit Mode"))
        self.update.setText(_translate("MainWindow", "Update"))
        self.ask.setText(_translate("MainWindow", "Please update to the latest version"))
        self.check.setText(_translate("MainWindow", "Check for updates"))
        self.label_5.setText(_translate("MainWindow", "v2.0.0"))
        self.validation_label.setText(_translate("MainWindow", "Brightskies Validation Team"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.welcome_tab), _translate("MainWindow", "Welcome"))
        self.back_btn_user.setText(_translate("MainWindow", "↩"))
        self.label_9.setText(_translate("MainWindow", "Asset Name"))
        self.asset_name.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial,sans-serif\'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "Asset Tag"))
        self.label_16.setText(_translate("MainWindow", "Serial"))
        self.label_17.setText(_translate("MainWindow", "Checked Out To"))
        self.label_18.setText(_translate("MainWindow", "Owner"))
        self.validation_label_2.setText(_translate("MainWindow", "Brightskies Validation Team"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.user_tab), _translate("MainWindow", "User Mode"))
        self.back_btn_user_2.setText(_translate("MainWindow", "↩"))
        self.password_label_2.setText(_translate("MainWindow", "Password"))
        self.label_excel.setText(_translate("MainWindow", "Excel"))
        self.pushButton_login.setText(_translate("MainWindow", "Login"))
        self.pushButton_browse_audit.setText(_translate("MainWindow", "Browse"))
        self.validation_label_7.setText(_translate("MainWindow", "Brightskies Validation Team"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "login"))
        self.start_scan_label.setText(_translate("MainWindow", "Start Scanning..."))
        self.back_btn_audit.setText(_translate("MainWindow", "↩"))
        self.label_8.setText(_translate("MainWindow", "All Brightskies Assets Number"))
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial,sans-serif\'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "All Mahle Assets Number"))
        self.label_12.setText(_translate("MainWindow", "Audit Assets Number"))
        self.label_13.setText(_translate("MainWindow", "Remaining Assets"))
        self.label_14.setText(_translate("MainWindow", "Scanned Assets"))
        self.FinishAudit.setText(_translate("MainWindow", "Finish Audit"))
        self.ShowStatistics.setText(_translate("MainWindow", "Show Statistics"))
        self.validation_label_4.setText(_translate("MainWindow", "Audit"))
        self.validation_label_5.setText(_translate("MainWindow", "Date   "))
        self.validation_label_3.setText(_translate("MainWindow", "Brightskies Validation Team"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.audit_tab), _translate("MainWindow", "Audit Mode"))
        self.back_btn_stats.setText(_translate("MainWindow", "↩"))
        self.label_7.setText(_translate("MainWindow", "Statistics :"))
        self.validation_label_8.setText(_translate("MainWindow", "Brightskies Validation Team"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Statistics_tab), _translate("MainWindow", "Statistics"))
import r_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
