# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 631)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setStyleSheet("/* Main Window */\n"
"QMainWindow {\n"
"    background-color: #f0f4f8;\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"}\n"
"\n"
"/* Tab Widget */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #cccccc;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #dce4ec;\n"
"    color: #004c8c;\n"
"    border: 1px solid #aaaaaa;\n"
"    padding: 10px;\n"
"    min-width: 120px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #004c8c;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    color: #004c8c;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Push Buttons */\n"
"QPushButton {\n"
"    background-color: #008cba;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005f7a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003f50;\n"
"}\n"
"\n"
"/* Group Boxes */\n"
"QGroupBox {\n"
"    border: 2px solid #004c8c;\n"
"    border-radius: 5px;\n"
"    margin-top: 20px;\n"
"    color: #004c8c;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* Text Edit */\n"
"QTextEdit {\n"
"    background-color: #ffffff;\n"
"    color: #004c8c;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"/* Line Edit */\n"
"QLineEdit {\n"
"    background-color: #ffffff;\n"
"    color: #004c8c;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* Combo Box */\n"
"QComboBox {\n"
"    background-color: #ffffff;\n"
"    color: #004c8c;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #008cba;\n"
"}\n"
"\n"
"/* Status Bar */\n"
"QStatusBar {\n"
"    background-color: #004c8c;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Scroll Bar */\n"
"QScrollBar:vertical {\n"
"    background-color: #dce4ec;\n"
"    width: 12px;\n"
"    margin: 20px 0 20px 0;\n"
"    border: 1px solid #aaaaaa;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #004c8c;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background-color: #dce4ec;\n"
"    border: 1px solid #aaaaaa;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Tool Bar */\n"
"QToolBar {\n"
"    background-color: #004c8c;\n"
"    border-bottom: 1px solid #cccccc;\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: #005f7a;\n"
"}")
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly|QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhEmailCharactersOnly|QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhLatinOnly|QtCore.Qt.ImhLowercaseOnly|QtCore.Qt.ImhUppercaseOnly|QtCore.Qt.ImhUrlCharactersOnly)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.welcome_tab = QtWidgets.QWidget()
        self.welcome_tab.setObjectName("welcome_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.welcome_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.label_6 = QtWidgets.QLabel(self.welcome_tab)
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.welcome_tab)
        self.label_5.setMinimumSize(QtCore.QSize(61, 41))
        self.label_5.setMaximumSize(QtCore.QSize(291, 41))
        self.label_5.setStyleSheet("background-image: url(:/JAKYA/JAKYA_LOGO.jpg);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        spacerItem2 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        spacerItem3 = QtWidgets.QSpacerItem(20, 78, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem4 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.validation_label_6 = QtWidgets.QLabel(self.welcome_tab)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.validation_label_6.setFont(font)
        self.validation_label_6.setObjectName("validation_label_6")
        self.verticalLayout_3.addWidget(self.validation_label_6)
        spacerItem5 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.user_btn = QtWidgets.QPushButton(self.welcome_tab)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.user_btn.setFont(font)
        self.user_btn.setObjectName("user_btn")
        self.horizontalLayout_5.addWidget(self.user_btn)
        self.audit_btn = QtWidgets.QPushButton(self.welcome_tab)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.audit_btn.setFont(font)
        self.audit_btn.setObjectName("audit_btn")
        self.horizontalLayout_5.addWidget(self.audit_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        spacerItem7 = QtWidgets.QSpacerItem(248, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11.addLayout(self.verticalLayout_9)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem8 = QtWidgets.QSpacerItem(628, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.validation_label = QtWidgets.QLabel(self.welcome_tab)
        self.validation_label.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.validation_label.setFont(font)
        self.validation_label.setObjectName("validation_label")
        self.gridLayout_4.addWidget(self.validation_label, 7, 0, 1, 2)
        self.ask = QtWidgets.QLabel(self.welcome_tab)
        self.ask.setObjectName("ask")
        self.gridLayout_4.addWidget(self.ask, 3, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.welcome_tab)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 2px solid #2196F3;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"    color: black;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #2196F3;\n"
"    width: 20px;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 5, 0, 1, 2)
        self.update = QtWidgets.QPushButton(self.welcome_tab)
        self.update.setObjectName("update")
        self.gridLayout_4.addWidget(self.update, 3, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.welcome_tab)
        self.label.setMinimumSize(QtCore.QSize(125, 91))
        self.label.setMaximumSize(QtCore.QSize(121, 91))
        self.label.setStyleSheet("background-image: url(:/logo/BrightLogo.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        spacerItem9 = QtWidgets.QSpacerItem(17, 358, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.check = QtWidgets.QPushButton(self.welcome_tab)
        self.check.setObjectName("check")
        self.gridLayout_4.addWidget(self.check, 6, 0, 1, 2)
        self.tabWidget.addTab(self.welcome_tab, "")
        self.user_tab = QtWidgets.QWidget()
        self.user_tab.setObjectName("user_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.user_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.back_btn_user = QtWidgets.QPushButton(self.user_tab)
        self.back_btn_user.setMinimumSize(QtCore.QSize(25, 25))
        self.back_btn_user.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.back_btn_user.setFont(font)
        self.back_btn_user.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;    /* Background color of the button */\n"
"    border: none;                 /* Remove default border */\n"
"    border-radius: 12px;          /* Makes the button circular (half of width/height) */\n"
"    width: 25px;                  /* Width of the button */\n"
"    height: 25px;                 /* Height of the button */\n"
"    color: white;                 /* Color of the arrow */\n"
"    font-size:25px;              /* Size of the arrow */\n"
"    font-weight: bold;            /* Bold arrow */\n"
"    text-align: center;           /* Center the arrow */\n"
"    padding: 0px;                 /* Remove any padding */\n"
"}\n"
"")
        self.back_btn_user.setObjectName("back_btn_user")
        self.verticalLayout_2.addWidget(self.back_btn_user)
        spacerItem10 = QtWidgets.QSpacerItem(20, 148, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 2, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem11 = QtWidgets.QSpacerItem(706, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.label_2 = QtWidgets.QLabel(self.user_tab)
        self.label_2.setMinimumSize(QtCore.QSize(125, 91))
        self.label_2.setMaximumSize(QtCore.QSize(121, 91))
        self.label_2.setStyleSheet("background-image: url(:/logo/BrightLogo.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 1, 1, 2)
        spacerItem12 = QtWidgets.QSpacerItem(20, 98, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem12, 1, 2, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem13)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_4 = QtWidgets.QLabel(self.user_tab)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.textBrowser = QtWidgets.QTextBrowser(self.user_tab)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textBrowser.setStyleSheet("QTextBrowser {\n"
"    background-color: #ffffff; /* Background color of the text browser */\n"
"    border: 1px solid #000000; /* Border color and width */\n"
"    border-radius: 12px; /* Radius to round the edges */\n"
"    padding: 10px; /* Padding inside the text browser */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_12.addWidget(self.textBrowser)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_12)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem14)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_7 = QtWidgets.QLabel(self.user_tab)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_14.addWidget(self.label_7)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.user_tab)
        self.textBrowser_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textBrowser_2.setStyleSheet("QTextBrowser {\n"
"    background-color: #ffffff; /* Background color of the text browser */\n"
"    border: 1px solid #000000; /* Border color and width */\n"
"    border-radius: 12px; /* Radius to round the edges */\n"
"    padding: 5px; /* Padding inside the text browser */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.horizontalLayout_14.addWidget(self.textBrowser_2)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem15)
        self.gridLayout_2.addLayout(self.horizontalLayout_16, 2, 0, 1, 3)
        spacerItem16 = QtWidgets.QSpacerItem(17, 55, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem16, 3, 2, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem17 = QtWidgets.QSpacerItem(108, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem17)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.user_tab)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.user_tab)
        self.textBrowser_3.setMinimumSize(QtCore.QSize(260, 0))
        self.textBrowser_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textBrowser_3.setStyleSheet("QTextBrowser {\n"
"    background-color: #ffffff; /* Background color of the text browser */\n"
"    border: 1px solid #000000; /* Border color and width */\n"
"    border-radius: 12px; /* Radius to round the edges */\n"
"    padding: 10px; /* Padding inside the text browser */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.horizontalLayout_13.addWidget(self.textBrowser_3)
        self.label_15 = QtWidgets.QLabel(self.user_tab)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15)
        self.lineEdit = QtWidgets.QLineEdit(self.user_tab)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_13.addWidget(self.lineEdit)
        self.pushButton_Scan = QtWidgets.QPushButton(self.user_tab)
        self.pushButton_Scan.setObjectName("pushButton_Scan")
        self.horizontalLayout_13.addWidget(self.pushButton_Scan)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_13)
        spacerItem18 = QtWidgets.QSpacerItem(448, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem18)
        self.gridLayout_2.addLayout(self.horizontalLayout_17, 4, 0, 1, 3)
        spacerItem19 = QtWidgets.QSpacerItem(20, 118, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem19, 5, 2, 1, 1)
        self.validation_label_2 = QtWidgets.QLabel(self.user_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.validation_label_2.setFont(font)
        self.validation_label_2.setObjectName("validation_label_2")
        self.gridLayout_2.addWidget(self.validation_label_2, 6, 0, 1, 2)
        self.tabWidget.addTab(self.user_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.back_btn_user_2 = QtWidgets.QPushButton(self.tab)
        self.back_btn_user_2.setMinimumSize(QtCore.QSize(25, 25))
        self.back_btn_user_2.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.back_btn_user_2.setFont(font)
        self.back_btn_user_2.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;    /* Background color of the button */\n"
"    border: none;                 /* Remove default border */\n"
"    border-radius: 12px;          /* Makes the button circular (half of width/height) */\n"
"    width: 25px;                  /* Width of the button */\n"
"    height: 25px;                 /* Height of the button */\n"
"    color: white;                 /* Color of the arrow */\n"
"    font-size:25px;              /* Size of the arrow */\n"
"    font-weight: bold;            /* Bold arrow */\n"
"    text-align: center;           /* Center the arrow */\n"
"    padding: 0px;                 /* Remove any padding */\n"
"}\n"
"")
        self.back_btn_user_2.setObjectName("back_btn_user_2")
        self.verticalLayout_12.addWidget(self.back_btn_user_2)
        spacerItem20 = QtWidgets.QSpacerItem(20, 148, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem20)
        self.gridLayout_3.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem21 = QtWidgets.QSpacerItem(710, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem21)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setMinimumSize(QtCore.QSize(125, 91))
        self.label_10.setMaximumSize(QtCore.QSize(121, 91))
        self.label_10.setStyleSheet("background-image: url(:/logo/BrightLogo.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_20.addWidget(self.label_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        spacerItem22 = QtWidgets.QSpacerItem(20, 138, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem22)
        self.gridLayout_3.addLayout(self.verticalLayout_11, 0, 1, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem23 = QtWidgets.QSpacerItem(288, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem23)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.password_label_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.password_label_2.setFont(font)
        self.password_label_2.setObjectName("password_label_2")
        self.horizontalLayout_18.addWidget(self.password_label_2)
        self.lineEdit_password_audit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_password_audit_2.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_password_audit_2.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoEditMenu|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhNoTextHandles|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_password_audit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_audit_2.setObjectName("lineEdit_password_audit_2")
        self.horizontalLayout_18.addWidget(self.lineEdit_password_audit_2)
        self.horizontalLayout.addLayout(self.horizontalLayout_18)
        self.pushButton_login = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setObjectName("pushButton_login")
        self.horizontalLayout.addWidget(self.pushButton_login)
        self.horizontalLayout_19.addLayout(self.horizontalLayout)
        spacerItem24 = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem24)
        self.verticalLayout_10.addLayout(self.horizontalLayout_19)
        spacerItem25 = QtWidgets.QSpacerItem(20, 48, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem25)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_excel = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_excel.setFont(font)
        self.label_excel.setObjectName("label_excel")
        self.horizontalLayout_3.addWidget(self.label_excel)
        self.lineEdit_excel_audit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_excel_audit.setMinimumSize(QtCore.QSize(500, 0))
        self.lineEdit_excel_audit.setObjectName("lineEdit_excel_audit")
        self.horizontalLayout_3.addWidget(self.lineEdit_excel_audit)
        self.pushButton_browse_audit = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_browse_audit.setFont(font)
        self.pushButton_browse_audit.setObjectName("pushButton_browse_audit")
        self.horizontalLayout_3.addWidget(self.pushButton_browse_audit)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        spacerItem26 = QtWidgets.QSpacerItem(20, 118, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem26)
        self.gridLayout_3.addLayout(self.verticalLayout_10, 1, 0, 1, 2)
        self.validation_label_7 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.validation_label_7.setFont(font)
        self.validation_label_7.setObjectName("validation_label_7")
        self.gridLayout_3.addWidget(self.validation_label_7, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.audit_tab = QtWidgets.QWidget()
        self.audit_tab.setObjectName("audit_tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.audit_tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.back_btn_audit = QtWidgets.QPushButton(self.audit_tab)
        self.back_btn_audit.setMinimumSize(QtCore.QSize(25, 25))
        self.back_btn_audit.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.back_btn_audit.setFont(font)
        self.back_btn_audit.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;    /* Background color of the button */\n"
"    border: none;                 /* Remove default border */\n"
"    border-radius: 12px;          /* Makes the button circular (half of width/height) */\n"
"    width: 25px;                  /* Width of the button */\n"
"    height: 25px;                 /* Height of the button */\n"
"    color: white;                 /* Color of the arrow */\n"
"    font-size:25px;              /* Size of the arrow */\n"
"    font-weight: bold;            /* Bold arrow */\n"
"    text-align: center;           /* Center the arrow */\n"
"    padding: 0px;                 /* Remove any padding */\n"
"}\n"
"")
        self.back_btn_audit.setObjectName("back_btn_audit")
        self.verticalLayout_18.addWidget(self.back_btn_audit)
        spacerItem27 = QtWidgets.QSpacerItem(20, 98, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem27)
        self.gridLayout_8.addLayout(self.verticalLayout_18, 0, 0, 1, 1)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem28 = QtWidgets.QSpacerItem(698, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem28)
        self.label_3 = QtWidgets.QLabel(self.audit_tab)
        self.label_3.setMinimumSize(QtCore.QSize(125, 91))
        self.label_3.setMaximumSize(QtCore.QSize(121, 91))
        self.label_3.setStyleSheet("background-image: url(:/logo/BrightLogo.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_21.addWidget(self.label_3)
        self.verticalLayout_20.addLayout(self.horizontalLayout_21)
        spacerItem29 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem29)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        spacerItem30 = QtWidgets.QSpacerItem(238, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem30)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_audit = QtWidgets.QLineEdit(self.audit_tab)
        self.lineEdit_audit.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEdit_audit.setText("")
        self.lineEdit_audit.setObjectName("lineEdit_audit")
        self.horizontalLayout_2.addWidget(self.lineEdit_audit)
        self.insert_btn_audit = QtWidgets.QPushButton(self.audit_tab)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.insert_btn_audit.setFont(font)
        self.insert_btn_audit.setObjectName("insert_btn_audit")
        self.horizontalLayout_2.addWidget(self.insert_btn_audit)
        self.horizontalLayout_48.addLayout(self.horizontalLayout_2)
        spacerItem31 = QtWidgets.QSpacerItem(258, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem31)
        self.verticalLayout_20.addLayout(self.horizontalLayout_48)
        self.gridLayout_8.addLayout(self.verticalLayout_20, 0, 1, 1, 2)
        spacerItem32 = QtWidgets.QSpacerItem(20, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem32, 1, 2, 1, 1)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_8 = QtWidgets.QLabel(self.audit_tab)
        self.label_8.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_43.addWidget(self.label_8)
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.audit_tab)
        self.textBrowser_6.setMinimumSize(QtCore.QSize(256, 29))
        self.textBrowser_6.setMaximumSize(QtCore.QSize(500, 33))
        self.textBrowser_6.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.horizontalLayout_43.addWidget(self.textBrowser_6)
        self.verticalLayout.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_11 = QtWidgets.QLabel(self.audit_tab)
        self.label_11.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_44.addWidget(self.label_11)
        self.textBrowser_13 = QtWidgets.QTextBrowser(self.audit_tab)
        self.textBrowser_13.setMinimumSize(QtCore.QSize(256, 0))
        self.textBrowser_13.setMaximumSize(QtCore.QSize(500, 33))
        self.textBrowser_13.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.horizontalLayout_44.addWidget(self.textBrowser_13)
        self.verticalLayout.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_12 = QtWidgets.QLabel(self.audit_tab)
        self.label_12.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_45.addWidget(self.label_12)
        self.textBrowser_14 = QtWidgets.QTextBrowser(self.audit_tab)
        self.textBrowser_14.setMinimumSize(QtCore.QSize(256, 0))
        self.textBrowser_14.setMaximumSize(QtCore.QSize(500, 33))
        self.textBrowser_14.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.horizontalLayout_45.addWidget(self.textBrowser_14)
        self.verticalLayout.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_13 = QtWidgets.QLabel(self.audit_tab)
        self.label_13.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_46.addWidget(self.label_13)
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.audit_tab)
        self.textBrowser_15.setMinimumSize(QtCore.QSize(256, 0))
        self.textBrowser_15.setMaximumSize(QtCore.QSize(500, 33))
        self.textBrowser_15.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.horizontalLayout_46.addWidget(self.textBrowser_15)
        self.verticalLayout.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_14 = QtWidgets.QLabel(self.audit_tab)
        self.label_14.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_47.addWidget(self.label_14)
        self.textBrowser_16 = QtWidgets.QTextBrowser(self.audit_tab)
        self.textBrowser_16.setMinimumSize(QtCore.QSize(256, 0))
        self.textBrowser_16.setMaximumSize(QtCore.QSize(500, 33))
        self.textBrowser_16.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.horizontalLayout_47.addWidget(self.textBrowser_16)
        self.verticalLayout.addLayout(self.horizontalLayout_47)
        self.verticalLayout_21.addLayout(self.verticalLayout)
        spacerItem33 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem33)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        spacerItem34 = QtWidgets.QSpacerItem(428, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem34)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        spacerItem35 = QtWidgets.QSpacerItem(20, 84, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_49.addItem(spacerItem35)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem36)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.validation_label_4 = QtWidgets.QLabel(self.audit_tab)
        self.validation_label_4.setMinimumSize(QtCore.QSize(35, 24))
        self.validation_label_4.setMaximumSize(QtCore.QSize(30, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.validation_label_4.setFont(font)
        self.validation_label_4.setObjectName("validation_label_4")
        self.horizontalLayout_7.addWidget(self.validation_label_4)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.audit_tab)
        self.textBrowser_4.setMinimumSize(QtCore.QSize(200, 0))
        self.textBrowser_4.setMaximumSize(QtCore.QSize(200, 33))
        self.textBrowser_4.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.horizontalLayout_7.addWidget(self.textBrowser_4)
        self.verticalLayout_19.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.validation_label_5 = QtWidgets.QLabel(self.audit_tab)
        self.validation_label_5.setMinimumSize(QtCore.QSize(30, 24))
        self.validation_label_5.setMaximumSize(QtCore.QSize(30, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.validation_label_5.setFont(font)
        self.validation_label_5.setObjectName("validation_label_5")
        self.horizontalLayout_8.addWidget(self.validation_label_5)
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.audit_tab)
        self.textBrowser_5.setMinimumSize(QtCore.QSize(200, 0))
        self.textBrowser_5.setMaximumSize(QtCore.QSize(200, 33))
        self.textBrowser_5.setStyleSheet("QTextBrowser {\n"
"     background-color: transparent; /* Makes the background transparent */\n"
"    color: #000000; /* Text color */\n"
"    font-family: Arial, sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar {\n"
"    width: 0px; /* Hide the vertical scrollbar */\n"
"    height: 0px; /* Hide the horizontal scrollbar */\n"
"}")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.horizontalLayout_8.addWidget(self.textBrowser_5)
        self.verticalLayout_19.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_49.addLayout(self.verticalLayout_19)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_49)
        self.verticalLayout_21.addLayout(self.horizontalLayout_50)
        self.gridLayout_8.addLayout(self.verticalLayout_21, 2, 0, 1, 3)
        self.validation_label_3 = QtWidgets.QLabel(self.audit_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.validation_label_3.setFont(font)
        self.validation_label_3.setObjectName("validation_label_3")
        self.gridLayout_8.addWidget(self.validation_label_3, 3, 0, 1, 2)
        self.tabWidget.addTab(self.audit_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JAKYA"))
        self.label_6.setText(_translate("MainWindow", "Asset Management Tool"))
        self.label_5.setText(_translate("MainWindow", "v2.0.0"))
        self.validation_label_6.setText(_translate("MainWindow", "  Select Mode"))
        self.user_btn.setText(_translate("MainWindow", "User Mode"))
        self.audit_btn.setText(_translate("MainWindow", "Audit Mode"))
        self.validation_label.setText(_translate("MainWindow", "Brightskies Validation Team"))
        self.ask.setText(_translate("MainWindow", "Please update to the latest version"))
        self.update.setText(_translate("MainWindow", "Update"))
        self.check.setText(_translate("MainWindow", "Check for updates"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.welcome_tab), _translate("MainWindow", "Welcome"))
        self.back_btn_user.setText(_translate("MainWindow", "↩"))
        self.label_4.setText(_translate("MainWindow", "Asset Name"))
        self.label_7.setText(_translate("MainWindow", "Model"))
        self.label_9.setText(_translate("MainWindow", "Assigne "))
        self.label_15.setText(_translate("MainWindow", "Asset Tag"))
        self.pushButton_Scan.setText(_translate("MainWindow", "Scan"))
        self.validation_label_2.setText(_translate("MainWindow", "Brightskies Validation Team"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.user_tab), _translate("MainWindow", "User Mode"))
        self.back_btn_user_2.setText(_translate("MainWindow", "↩"))
        self.password_label_2.setText(_translate("MainWindow", "Password"))
        self.pushButton_login.setText(_translate("MainWindow", "Login"))
        self.label_excel.setText(_translate("MainWindow", "Excel"))
        self.pushButton_browse_audit.setText(_translate("MainWindow", "Browse"))
        self.validation_label_7.setText(_translate("MainWindow", "Brightskies Validation Team"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "login"))
        self.back_btn_audit.setText(_translate("MainWindow", "↩"))
        self.insert_btn_audit.setText(_translate("MainWindow", "Scan for the asset"))
        self.label_8.setText(_translate("MainWindow", "All Brightskies Assets Number"))
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial,sans-serif\'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "All Mahle Assets Number"))
        self.label_12.setText(_translate("MainWindow", "Audit Assets Number"))
        self.label_13.setText(_translate("MainWindow", "Remaining Assets"))
        self.label_14.setText(_translate("MainWindow", "scanned Assets"))
        self.validation_label_4.setText(_translate("MainWindow", "Audit"))
        self.validation_label_5.setText(_translate("MainWindow", "Date"))
        self.validation_label_3.setText(_translate("MainWindow", "Brightskies Validation Team"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.audit_tab), _translate("MainWindow", "Audit Mode"))
import r_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
